server:
  port: 8888


#eureka
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka/

#socketIO 配置
hjx-coding:
  socket-hostname: localhost
  socket-port: 9092